version: '3.8'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    expose:
      - "9000"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
      - adminer:/var/www/adminer
      - website:/var/www/website
    networks:
      - inception
    depends_on:
      - wordpress
      - amdiner
      - website
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  amdiner:
    container_name: adminer
    env_file: .env
    volumes:
      - adminer:/var/www/adminer
    networks:
      - inception
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

  redis:
    container_name: redis
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - "9000"

  ftp:
    container_name: ftp
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - "20:20"
      - "21:21"
      - "40000-40005:40000-40005"

  cadvisor:
    container_name: cadvisor
    env_file: .env
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception
    build:
      context: requirements/bonus/cadvisor
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"

  website:
    container_name: website
    env_file: .env
    volumes:
      - website:/var/www/website
    networks:
      - inception
    build:
      context: requirements/bonus/website
      dockerfile: Dockerfile
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/$USERDOCKER/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/$USERDOCKER/data/mariadb'
  adminer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/$USERDOCKER/data/adminer'
  website:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/$USERDOCKER/data/website'

networks:
  inception:
    driver: bridge
